version: "3"

tasks:
  hello:
    desc: "Afficher un message simple"
    cmds:
      - echo "Hello depuis Taskfile sous Windows !"

  python-test:
    desc: "Exécuter un script Python exemple"
    cmds:
      - python -c "print('Hello Python !')"

  all:
    desc: "Exécute toutes les tâches"
    deps: [hello, python-test]

